name: build_and_test

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@main
        - name: win64-vstudio-debug
          run:  python3 fips build win64-vstudio-debug
        - name: win64-vstudio-release
          run:  python3 fips build win64-vstudio-release
        - name: d3d11-win64-vstudio-debug
          run:  python3 fips build d3d11-win64-vstudio-debug
        - name: d3d11-win64-vstudio-release
          run:  python3 fips build d3d11-win64-vstudio-release
        - name: sapp-win64-vstudio-debug
          run:  python3 fips build sapp-win64-vstudio-debug
        - name: sapp-win64-vstudio-release
          run:  python3 fips build sapp-win64-vstudio-release
        - name: sapp-d3d11-win64-vstudio-debug
          run:  python3 fips build sapp-d3d11-win64-vstudio-debug
        - name: sapp-d3d11-win64-vstudio-release
          run:  python3 fips build sapp-d3d11-win64-vstudio-release
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - name: osx-make-debug
          run:  python3 fips build osx-make-debug
        - name: osx-make-release
          run:  python3 fips build osx-make-release
        - name: metal-osx-make-debug
          run:  python3 fips build metal-osx-make-debug
        - name: metal-osx-make-release
          run:  python3 fips build metal-osx-make-release
        - name: sapp-metal-osx-make-debug
          run:  python3 fips build sapp-metal-osx-make-debug
        - name: sapp-metal-osx-make-release
          run:  python3 fips build sapp-metal-osx-make-release
    ios:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - name: ios-xcode-debug
          run:  python3 fips build ios-xcode-debug -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: ios-xcode-release
          run:  python3 fips build ios-xcode-release -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: metal-ios-xcode-debug
          run:  python3 fips build metal-ios-xcode-debug -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: metal-ios-xcode-release
          run:  python3 fips build metal-ios-xcode-release -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: sapp-ios-xcode-debug
          run:  python3 fips build sapp-ios-xcode-debug -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        - name: sapp-metal-ios-xcode-release
          run:  python3 fips build sapp-metal-ios-xcode-debug -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: prepare
          run:  |
            sudo apt-get update
            sudo apt-get install libgl1-mesa-dev libegl1-mesa-dev mesa-common-dev xorg-dev libasound-dev
            cmake --version
        - name: linux-make-debug
          run:  python3 fips build linux-make-debug
        - name: linux-make-release
          run:  python3 fips build linux-make-release
        - name: sapp-linux-make-debug
          run:  python3 fips build sapp-linux-make-debug
        - name: sapp-linux-make-release
          run:  python3 fips build sapp-linux-make-release
        - name: sapp-egl-gl-linux-make-debug
          run:  python3 fips build sapp-egl-gl-linux-make-debug
        - name: sapp-egl-gl-linux-make-release
          run:  python3 fips build sapp-egl-gl-linux-make-release
        - name: sapp-egl-gles3-linux-make-debug
          run:  python3 fips build sapp-egl-gles3-linux-make-debug
        - name: sapp-egl-gles3-linux-make-release
          run:  python3 fips build sapp-egl-gles3-linux-make-release
    webgl2:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: prepare
          run: |
            sudo apt-get install ninja-build
            python3 fips emsdk install latest
        - name: sapp-webgl2-wasm-ninja-debug
          run:  python3 fips build sapp-webgl2-wasm-ninja-debug
        - name: sapp-webgl2-wasm-ninja-release
          run:  python3 fips build sapp-webgl2-wasm-ninja-release
        - name: webgl2-wasm-ninja-debug
          run:  python3 fips build webgl2-wasm-ninja-debug
        - name: webgl2-wasm-ninja-release
          run:  python3 fips build webgl2-wasm-ninja-release
    wgpu:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: prepare
          run: |
            sudo apt-get install ninja-build
            python3 fips emsdk install latest
        - name: sapp-wgpu-wasm-ninja-debug
          run:  python3 fips build sapp-wgpu-wasm-ninja-debug
        - name: sapp-wgpu-wasm-ninja-release
          run:  python3 fips build sapp-wgpu-wasm-ninja-release
    android:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '8'
        - name: prepare
          run: |
            yes | python3 fips setup android
        - name: sapp-android-make-debug
          run: python3 fips build sapp-android-make-debug
        - name: sapp-android-make-release
          run: python3 fips build sapp-android-make-release
