---
platform: android
generator: Ninja
build_tool: ninja
build_type: Debug
cmake-toolchain: android.toolchain.cmake
defines:
    USE_SOKOL_APP: ON
    ANDROID_ABI: armeabi-v7a
    ANDROID_PLATFORM: android-28
