---
platform: android
generator: Unix Makefiles
build_tool: make
build_type: Release
cmake-toolchain: android.toolchain.cmake
defines:
    USE_SOKOL_APP: ON
    SOKOL_USE_OPENSLES: ON
    ANDROID_ABI: armeabi-v7a
    ANDROID_PLATFORM: android-28
