---
platform: emscripten
generator: Ninja
build_tool: vscode
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
defines:
    USE_SOKOL_APP: ON
    FIPS_EMSCRIPTEN_USE_WEBGL2: ON
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
    FIPS_EMSCRIPTEN_RELATIVE_SHELL_HTML: "webpage/shell.html"
    FIPS_EMSCRIPTEN_USE_CLOSURE: ON
