---
platform: emscripten 
generator: Ninja 
build_tool: ninja
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
defines:
    USE_SOKOL_APP: ON
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_WEBGL2: ON
    FIPS_EMSCRIPTEN_MEM_INIT_METHOD: 0
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
    FIPS_EMSCRIPTEN_RELATIVE_SHELL_HTML: "webpage/shell.html"
    FIPS_EMSCRIPTEN_USE_CLOSURE: ON

