---
platform: emscripten
generator: Ninja
build_tool: vscode_cmake
build_type: Release
cmake-toolchain: emscripten.toolchain.cmake
vscode_additional_defines: [ '__EMSCRIPTEN__', 'SOKOL_IMPL', 'SOKOL_D3D11', 'SOKOL_METAL', 'SOKOL_GLCORE33', 'SOKOL_GLES3', 'SOKOL_GLES2' ]
defines:
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_WEBGL2: ON
    FIPS_EMSCRIPTEN_MEM_INIT_METHOD: 0
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
    FIPS_EMSCRIPTEN_RELATIVE_SHELL_HTML: "webpage/shell.html"
    FIPS_EMSCRIPTEN_USE_CLOSURE: ON

